# Generated by Django 3.0 on 2020-12-19 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pictures", "0002_unsplashcollections_unsplashkeywords_unsplashphotos")
    ]

    operations = [
        migrations.RemoveField(model_name="unsplashkeywords", name="photo"),
        migrations.DeleteModel(name="UnsplashCollections"),
        migrations.DeleteModel(name="UnsplashKeywords"),
        migrations.DeleteModel(name="UnsplashPhotos"),
    ]
