# Generated by Django 3.0 on 2020-12-19 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("pictures", "0008_auto_20201219_0313")]

    operations = [migrations.RemoveField(model_name="images", name="image")]
