# Generated by Django 3.0 on 2020-12-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("pictures", "0011_auto_20201219_0316")]

    operations = [
        migrations.AddField(
            model_name="unsplashcollections",
            name="collection_title",
            field=models.TextField(null=True),
        )
    ]
