# Generated by Django 3.0 on 2020-12-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("pictures", "0013_auto_20201219_0342")]

    operations = [
        migrations.AddField(
            model_name="images",
            name="collection",
            field=models.CharField(max_length=255, null=True),
        )
    ]
