# Generated by Django 3.0 on 2020-12-19 19:45

from django.db import migrations
from django.contrib.postgres.operations import HStoreExtension, BtreeGinExtension, TrigramExtension, UnaccentExtension
class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0014_images_collection'),
    ]

    operations = [
        HStoreExtension(),
        BtreeGinExtension(),
        TrigramExtension(),
        UnaccentExtension()
    ]
