# Generated by Django 3.0 on 2020-12-20 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("pictures", "0018_auto_20201220_2008")]

    operations = [
        migrations.RenameField(
            model_name="images", old_name="image", new_name="image_photo"
        )
    ]
